version: '3'
services:
  nextjs:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    env_file:
      - .env.local
  mongo:
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongodb-data:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=franco
      - MONGO_INITDB_ROOT_PASSWORD=admin
volumes:
  mongodb-data:
