import Head from "next/head";
import PersonalFinances from "../personal";
import { useValidatePlan } from "@hooks/use-validate-plan";

export default function Home() {
  const { status } = useValidatePlan()
  if(status==='loading')return null

    return (
      <>
        <Head>
          <title>Finanzas Personales</title>
          <meta name="description" content="Generated by create next app" />
          <meta name="viewport" content="width=device-width, initial-scale=1" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
        <main>
          <div className="container-graphics">
            <PersonalFinances />
          </div>
        </main>
      </>
    );
}