import Head from "next/head";
import PersonalFinances from "./personal";
import { useSession } from "next-auth/react";
import { useSelector } from "react-redux";
import LogButton from "@/src-client/components/LogIn/button";

export default function Home() {
  const {data: session} = useSession({required: true})
  const user = useSelector((state : any) => state.PersonalReducer.user)
  if(session && session.user && user.status !== 'disabled'){

    return (
      <>
        <Head>
          <title>Finanzas Personales</title>
          <meta name="description" content="Generated by create next app" />
          <meta name="viewport" content="width=device-width, initial-scale=1" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
        <main>
          <div className="container-graphics">
            <PersonalFinances />
          </div>
        </main>
      </>
    );
  } else if(session && session.user && user.status === 'disabled') {
    return (
      <>
      <h1>Tu cuenta aun no ha sido activada.</h1>
      <h3>Para activarla podes enviar un correo a .........@gmail.com</h3>
      </>
    )
  } else {
    <>
    <h1>Aun no has iniciado sesion</h1>
    <LogButton />
    </>
  }
}
