export const catTransactions = ['Hogar', 'Transporte', 'Alimentacion', 'Salud', 'Entretenimiento', 'Educación', 'Deudas', 'Ahorro e inversión', 'Vestimenta y cuidado personal', 'Regalos y donaciones', 'Otros' ]
export const catTransactionsEntries = {
  Hogar: true,
  Transporte: true,
  'Alimentacion': true,
  Salud: true,
  Entretenimiento: true,
  Educación: true,
  'Deudas': true,
  'Ahorro e inversión': true,
  'Vestimenta y cuidado personal': true,
  'Regalos y donaciones': true,
  Otros: true,
}
export const incomesPersonal =['Salario',
  'Trabajos independientes',
  'Alquiler',
  'Inversiones',
  'Regalías',
  'Intereses bancarios',
  'Dividendos',
  'Ganancias por ventas',
  'Consultoría',
  'Enseñanza/tutoría',
  'Otros']