export const incomesCompany = ['Venta de productos',
    'Servicios',
    'Alquileres',
    'Comisiones',
    'Financiamiento',
    'Eventos',
    'Publicidad',
    'Otros' ]
export const expensesCompany = ['Mercaderías',
    'Personal',
    'Alquileres',
    'Marketing',
    'Administrativos',
    'Tecnología',
    'Viaje',
    'Financieros',
    'Impuestos y licencias',
    'Mantenimiento',
    'Gastos legales',
    'Seguros',
    'Otros']